FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NUXT_HOST=0.0.0.0
ENV NUXT_DB_URL="postgres://root:123@172.24.0.2:5432/dev"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS dev
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base
COPY --from=dev /app/node_modules /app/node_modules
EXPOSE 3000
CMD [ "pnpm", "start" ]